## 数组操作

NumPy提供了一些方便的函数来操作数组，包括连接数组、分割数组、改变数组形状和交换数组维度等。

1. 连接数组：使用np.concatenate()函数沿指定轴连接数组

In [12]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

# 沿行方向连接数组
result = np.concatenate((a, b), axis=0)
print("r1:\n", result)
# Join a sequence of arrays along an existing axis. axis不能超过数组的维度
result = np.concatenate((a, b), axis=1)
print("r2:\n", result)

r1:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
r2:
 [[1 2 5 6]
 [3 4 7 8]]


2. 分割数组：使用np.split()函数将数组分割为多个子数组

In [24]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
# 将数组分割为2个子数组
result = np.array_split(a, 2)
print(result)
# 将数组分割为3个子数组
result = np.array_split(a, 3)
print(result)

[array([1, 2, 3]), array([4, 5])]
[array([1, 2]), array([3, 4]), array([5])]


np.array_split()是 NumPy 中用于将数组拆分成多个子数组的函数。它接受三个参数：数组、拆分的位置或拆分的索引、拆分的轴。当我们拆分多维数组时，又会发生什么呢？

In [34]:
import numpy as np

# 创建一个数组
arr = np.arange(1, 13).reshape(3, 4)
print("原始数组：")
print(arr)

# 对数组进行拆分
sub_arrays = np.array_split(arr, 2, axis=1)
print("\n拆分后的子数组：")
for sub_arr in sub_arrays:
    print(sub_arr)

原始数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

拆分后的子数组：
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]


wahoo，很明显，拆分根据axis参数，只获取二维原始数组（2-D)中的前2列，即在原始二维数组arr的每个元素下标为axis=1的位置停止了。

在这个示例中，我们创建了一个 3 行 4 列的数组 arr，然后使用 np.array_split(arr, 2， axis=1) 将数组拆分成两个子数组。拆分的结果是一个包含两个数组的列表 sub_arrays，要注意的是，拆分的轴参数axis是可选的。如果没有提供轴参数，np.array_split() 默认在 0 轴（行）上进行拆分。

3. 改变数组形状：使用np.reshape()函数改变数组的形状

In [51]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
# 将数组转换为2x3的形状
result = np.reshape(a, (2, 3))
print(result)

result = np.reshape(result, (6, 1))
print(result)

# 改变层级后维度相乘的结果数量需要等于原元素个数，否则报错：ValueError
# result = np.reshape(result, (7, 1))
# print(result)

[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


4. 交换数组维度：使用np.transpose()函数交换数组的维度

In [52]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
# 交换数组的维度
result = np.transpose(a)

print(result)

[[1 4]
 [2 5]
 [3 6]]
