NumPy数组广播是一种自动执行元素级操作的机制。它可以使具有不同形状的数组在算术运算中表现得像具有相同形状的数组一样。这种机制大大简化了对不同形状数组之间的操作。

下面是一个示例代码，演示了如何使用广播来执行数组的加法运算：

In [7]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


在上面的代码中，arr1 是一个形状为 (2, 3) 的二维数组，arr2 是一个形状为 (3,) 的一维数组。根据广播规则，arr2 实际上被扩展为了形状为 (2, 3) 的二维数组，其中每一行都是 arr2。然后，数组 arr1 和扩展后的 arr2 进行元素级加法运算，得到了最终的结果。

通过广播机制，我们可以直接对不同大小的数组执行加法操作，而不需要手动进行数组形状的调整。这样可以大大简化代码，并提高效率。同时，广播机制也可以应用于其他的 NumPy 函数和运算中。

In [8]:
print(arr1 + 10)
print(arr1 + np.array([10]))
# ValueError: operands could not be broadcast together with shapes (2,3) (2,) 
# print(arr1 + np.array([1, 2]))

[[11 12 13]
 [14 15 16]]
[[11 12 13]
 [14 15 16]]
