## numpy基础数据结构

NumPy是Python中用于数值计算和科学计算的重要库之一，提供了高效的多维数组（ndarray）对象和各种用于数组计算的函数和工具。在NumPy中，数组是基本的数据结构，可以用于存储和处理任何数值类型的数据。

1.一维数组: 一维数组也称为一阶数组，是最基本的数组。它包含一系列相同数据类型的元素，并按线性方式排列。可以通过索引访问数组中的元素。

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


2. 二维数组: 二维数组也称为二阶数组，可以理解为包含多个一维数组的数组，称为行和列。二维数组中每个元素由两个坐标索引指定，一个表示行号，一个表示列号。

In [ ]:
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


3. 三维数组: 三维数组也称为三阶数组，由多个二维数组组成，称为深度。每个元素由三个坐标索引指定，分别表示行，列和深度。

In [ ]:
import numpy as np
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


4. 多维数组: 多维数组可以理解为包含多个n-1维数组的数组，可以是任意维数。在NumPy中，可以用ndim属性来获取数组的维数。

In [ ]:
import numpy as np
arr4 = np.array([1, 2, 3], ndmin=5)
print(arr4)
print('数组的维度：', arr4.ndim)

[[[[[1 2 3]]]]]
数组的维度： 5


NumPy中的数组数据结构比Python中的list更加灵活和高效，因为NumPy中的数组是按照连续的块存储在内存中的，并且提供了各种数组操作函数和算法，可以满足大量数值计算和科学计算的需求。

## 数组的属性
NumPy数组有许多重要的属性，可以帮助我们了解数组的特征。

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("数组形状:", arr.shape)
print("数组维度:", arr.ndim)
print("数组元素总数:", arr.size)
print("数组数据类型:", arr.dtype)

数组形状: (5,)
数组维度: 1
数组元素总数: 5
数组数据类型: int32
