## 索引&切片基础

NumPy是Python中用于数值计算和科学计算的重要库之一，提供了高效的多维数组（ndarray）对象和各种用于数组计算的函数和工具。在NumPy中，可以使用索引和切片来访问数组元素和子数组。
1. 索引：
在NumPy中，可以使用方括号[]访问数组中的元素，索引从0开始。可以使用整数或整数序列来指定索引，多个索引可以使用逗号分隔。

In [1]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr[0, 1])       # 2
print(arr[1])          # [4 5 6]
print(arr[1][2])       # 6
print(arr[1, -2:])     # [5 6]

2
[4 5 6]
6
[5 6]


2. 切片
   在NumPy中，可以使用切片来访问数组中的子数组，切片用冒号分隔开始和结束索引，返回的是原始数组的子数组，没有进行数据拷贝。可以使用[start:end:step]来定制切片。
   

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])        # [2 3 4 5]
print(arr[:4])         # [1 2 3 4]
print(arr[4:])         # [5 6 7]
print(arr[::2])        # [1 3 5 7]

[2 3 4 5]
[1 2 3 4]
[5 6 7]
[1 3 5 7]


对于多维数组，可以对不同维度的切片使用不同的语法：

In [6]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[:2, 1:])      # [[2 3]
                        #  [5 6]]
print(arr[1, :2])       # [4 5]

print(arr[2, ::-1])     # [9 8 7] 倒序输出

[[2 3]
 [5 6]]
[4 5]
[9 8 7]


需要注意的是，NumPy中的切片与Python中的切片略有不同，主要体现在切片结束点是开区间，不包含结束索引对应的元素，而Python中是闭区间，包含结束索引对应的元素。

## 高级索引技巧

NumPy提供了多种高级索引技巧，用于访问数组的特定位置。以下是三种常用的高级索引方法：

1. 整数数组索引：使用一个整数数组作为索引，可以选择数组中的特定元素。

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
# 使用整数数组索引获取指定位置的元素
indices = np.array([1, 3])
result = a[indices]
print(result)

[2 4]


2. 布尔数组索引：使用一个布尔数组作为索引，可以根据布尔数组的元素值来选择数组中的元素。

In [7]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
# 使用布尔数组索引选择大于3的元素
mask = a > 3
# 还可以直接按布尔数组进行匹配
# mask = np.array([False, False, False, True, True])
print(mask)
result = a[mask]
print(result)

[False False False  True  True]
[4 5]


3. 花式索引(Fancy indexing)：使用整数数组或整数列表作为索引，可以根据指定的索引位置选择数组中的元素。

In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
# 使用花式索引获取指定位置的元素
indices = np.array([0, 2, 4])
result = a[indices]
print(result)

[1 3 5]


多维数组的操作与此类似，如果使用负整数，索引会从末尾倒着开始哦。