NumPy是Python中用于数值计算和科学计算的重要库之一，提供了高效的多维数组（ndarray）对象和各种用于数组计算的函数和工具。在NumPy中，可以使用索引和切片来访问数组元素和子数组。
1. 索引：
在NumPy中，可以使用方括号[]访问数组中的元素，索引从0开始。可以使用整数或整数序列来指定索引，多个索引可以使用逗号分隔。

In [1]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr[0, 1])       # 2
print(arr[1])          # [4 5 6]
print(arr[1][2])       # 6
print(arr[1, -2:])     # [5 6]

2
[4 5 6]
6
[5 6]


2. 切片
   在NumPy中，可以使用切片来访问数组中的子数组，切片用冒号分隔开始和结束索引，返回的是原始数组的子数组，没有进行数据拷贝。可以使用[start:end:step]来定制切片。
   

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])        # [2 3 4 5]
print(arr[:4])         # [1 2 3 4]
print(arr[4:])         # [5 6 7]
print(arr[::2])        # [1 3 5 7]

[2 3 4 5]
[1 2 3 4]
[5 6 7]
[1 3 5 7]


对于多维数组，可以对不同维度的切片使用不同的语法：

In [6]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr[:2, 1:])      # [[2 3]
                        #  [5 6]]
print(arr[1, :2])       # [4 5]

print(arr[2, ::-1])     # [9 8 7] 倒序输出

[[2 3]
 [5 6]]
[4 5]
[9 8 7]


需要注意的是，NumPy中的切片与Python中的切片略有不同，主要体现在切片结束点是开区间，不包含结束索引对应的元素，而Python中是闭区间，包含结束索引对应的元素。