NumPy提供了生成各种分布随机数的函数和工具，这些随机数生成器是伪随机数，基于确定性算法产生的序列，但是看起来像是随机的。
下面是一些常用的随机数函数：
1. np.random.random(size=None)
   
该函数返回一个[0, 1)之间的随机浮点数，可以使用size参数来指定要生成的随机数数组的形状。

In [4]:
import numpy as np
print(np.random.random())          # 生成一个[0, 1)之间的随机浮点数
print(np.random.random(size=5))    # 生成一个包含5个[0, 1)之间的随机浮点数的一维数组
print(np.random.random(size=(2, 3)))# 生成一个2 x 3的二维数组，其中包含[0, 1)之间的随机浮点数
print(np.random.random(size=5) * 100)

0.8838692582576403
[0.06030192 0.34653048 0.072524   0.20613905 0.10501264]
[[0.39827106 0.08136065 0.69861865]
 [0.46925107 0.33687736 0.04750219]]
[97.53563287  2.83104426 47.39646999 14.45399545  1.11773192]


2. np.random.randint(low, high=None, size=None, dtype=‘l’)
   
该函数返回一个位于闭区间 [low, high) 之间的随机整数（不包括 high)，可以使用 size 参数来指定所需随机数数组的形状，使用 dtype 参数来指定数据类型。
ini 代码解读复制代码

In [6]:
import numpy as np
print(np.random.randint(0, 5))           # 生成一个[0, 5)之间的随机整数
print(np.random.randint(1, size=5))      # 生成一个[0, 1)之间的随机整数数组
print(np.random.randint(1, 5, size=(2,3)))# 生成一个2 x 3的随机整数数组，其中元素位于闭区间[1, 5)
print(np.random.randint(1, 5, size=(2,3), dtype=np.int16)) # 指定数组数据类型为int16

0
[0 0 0 0 0]
[[3 3 4]
 [3 1 1]]
[[1 2 3]
 [3 1 2]]


3. np.random.normal(loc=0.0, scale=1.0, size=None)

该函数返回一个满足指定均值和标准差的高斯分布样本，可以使用loc指定均值，使用scale指定标准差。

In [8]:
import numpy as np
print(np.random.normal())           # 生成一个均值为0，标准差为1的高斯分布样本
print(np.random.normal(size=5))     # 生成包含5个高斯分布样本的一维数组
print(np.random.normal(loc=2.0, scale=0.5, size=(2,3))) # 生成2 x 3的数组，均值为2.0，标准差为0.5

1.3433393029297949
[-0.75853984  0.34992885  0.06917252 -1.18565113 -0.05580368]
[[1.50714459 2.10643909 1.55322006]
 [1.66937444 1.95246478 2.27885471]]


4. np.random.random_sample(size=None)

该函数返回一个[0, 1)之间的随机浮点数，可以使用size参数来指定要生成的随机数数组的形状。

In [10]:
import numpy as np
print(np.random.random_sample())      # 生成一个[0, 1)之间的随机浮点数
print(np.random.random_sample(size=5))# 生成包含5个[0, 1)之间的随机浮点数的一维数组
print(np.random.random_sample(size=(2, 3))) # 生成2 x 3的随机浮点数数组，元素位于[0, 1)

0.337748667953907
[0.23458455 0.98004217 0.98734811 0.72383027 0.27129989]
[[0.60119562 0.91635987 0.859324  ]
 [0.32428681 0.39037725 0.29036753]]


5. np.random.seed(seed=None)

该函数用于生成随机数生成器的种子，可以使用整数指定特定的种子，这样每次生成的随机序列都将相同。如果不指定种子，则使用系统时间作为种子。

In [16]:
import numpy as np
np.random.seed(10)       # 指定随机种子为10
print(np.random.random()) # 生成0.77132064
np.random.seed(10)
print(np.random.random()) # 生成0.77132064，与上面的一样

0.771320643266746
0.771320643266746
