NumPy（Numerical Python）是用于科学计算和数据分析的Python库之一，在其子模块中包含了许多用于处理多维数组的通用函数（ufuncs）。这些通用函数可以对数组中的元素进行逐个操作，产生一个或多个输出，通常不改变输入数据的形状大小。以下是NumPy中一些常用的通用函数：

1. 算术运算：add、subtract、multiply、divide、power、mod、remainder、abs

In [3]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
print(np.add(x, y))     # [5 7 9]
print(np.subtract(x, y)) # [-3 -3 -3]
print(np.multiply(x, y)) # [4 10 18]
print(np.divide(x, y))   # [0.25 0.4  0.5 ]
print(np.power(x, 2))    # [1 4 9]
print(np.mod(y, 2))      # [0 1 0]  %
print(np.remainder(y, 2)) # [0 1 0] 取余
print(np.abs([-1,-2,3]))     # [1 2 3]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[0 1 0]
[0 1 0]
[1 2 3]


2. 统计函数：mean、std、var、sum、prod、min、max

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))   # 2.5 求平均值
print(np.median(arr)) # 2.5 中位数
print(np.std(arr))    # 1.118033988749895 计算沿指定轴的标准偏差。
print(np.var(arr))    # 1.25 计算沿指定轴的方差。
print(np.sum(arr))    # 10 返回给定轴上数组元素的求和。
print(np.prod(arr))   # 24 返回给定轴上数组元素的乘积。
print(np.min(arr))    # 1 返回给定轴上数组元素的最小值。
print(np.max(arr))    # 4 返回给定轴上数组元素的最大值。

2.5
2.5
1.118033988749895
1.25
10
24
1
4


3. 三角函数：sin、cos、tan、arcsin、arccos、arctan

In [10]:
import numpy as np
x = np.array([0, 30, 45, 60, 90])
print(np.sin(np.deg2rad(x)))  # [0.         0.5        0.70710678 0.8660254  1.        ]
print(np.cos(np.deg2rad(x)))  # [1.         0.8660254  0.70710678 0.5        0.        ]
print(np.tan(np.deg2rad(x)))  # [0.         0.57735027 1.         1.73205081        inf]
print(np.arcsin(0.5))         # 0.5235987755982989
print(np.arccos(0.5))         # 1.0471975511965979
print(np.arctan(1))           # 0.7853981633974483

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
0.5235987755982989
1.0471975511965979
0.7853981633974483


4. 逻辑运算：greater、less、equal、logical_and、logical_or

In [13]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([2, 2, 2])
print(np.greater(x, y))            # [False False  True]
print(np.less(x, y))               # [ True False False]
print(np.equal(x, y))              # [False  True False]
print(x > 1)                        # [False  True  True]
print(np.logical_and(x > 1, y < 3)) # [ True  True False]
print(np.logical_or(x < 2, y > 2))  # [ True False  True]

[False False  True]
[ True False False]
[False  True False]
[False  True  True]
[False  True  True]
[ True False False]


这些通用函数是使用NumPy进行科学计算和数据分析的基础，掌握它们是非常重要的。需要注意的是，在处理大量数据时，使用通用函数可以显著提高程序的执行速度。